### PR TITLE
Remove the visual-diff action from the master branch

### PR DESCRIPTION
**Pull request by svanherk**
The last usage is in https://github.com/Brightspace/activities-test, which I'm going to move to the Graveyard once the automation is done (already talked to the devs about it).

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]
🎉

**Comment by eKoopmans** [comment]
Novice question: why are we removing this?

**Comment by svanherk** [comment]
> Novice question: why are we removing this?

Last November we moved from the `master` branch to the `main` branch and updated a number of places, but a lot of places are still pointing directly to `master` (like [this](https://search.d2l.dev/search?project=Brightspace&project=Brightspace-Configs&project=BrightspaceHypermediaComponents&project=BrightspaceUI&project=BrightspaceUILabs&project=lms&project=Scratch&full=%22BrightspaceUI%2Factions%2Fsemantic-release%40master%22&defs=&refs=&path=&hist=&type=&xrd=&nn=7&si=full&si=full)).  Once we remove all usages of `BrightspaceUI/actions/<the_action>@master`, we can remove that action from the `master` branch so no one can add it back.  The `master` versions aren't getting any updates

**Comment by eKoopmans** [comment]
Excellent, thanks!

**Pull request merged**
